/**
 * `fit-terrain substrate init --cwd <dir>` — offline scaffold. Writes one
 * timestamped starter migration into `<cwd>/supabase/migrations/`: the
 * `substrate` schema, service-role grants, and one commented example view
 * per contract relation, generated from `SUBSTRATE_CONTRACT` so the
 * scaffold and the `check` probe cannot drift apart. The consumer edits
 * the example views to map its own tables onto the contract columns.
 */

import path from "node:path";
import { isoTimestamp } from "@forwardimpact/libutil";
import { formatSuccess } from "@forwardimpact/libcli";
import { SUBSTRATE_CONTRACT } from "../substrate/contract.js";

function exampleView(name, { required, columns }) {
  const columnList = columns.map((c) => `--   <expr> as ${c}`).join(",\n");
  return [
    `-- ${required ? "Required" : "Optional"} relation: substrate.${name}`,
    `-- Map your own schema onto the contract columns, then uncomment:`,
    `-- create view substrate.${name} as`,
    `-- select`,
    columnList,
    `-- from <your_table>;`,
  ].join("\n");
}

function migrationSql() {
  const views = Object.entries(SUBSTRATE_CONTRACT.relations)
    .map(([name, rel]) => exampleView(name, rel))
    .join("\n\n");
  return `-- Substrate Contract starter migration (generated by
-- \`fit-terrain substrate init\`). Normative reference:
-- https://www.forwardimpact.team/docs/libraries/substrate-contract/index.md

create schema ${SUBSTRATE_CONTRACT.schema};
grant usage on schema ${SUBSTRATE_CONTRACT.schema} to service_role;

${views}

-- Grants run after your views exist:
grant select on all tables in schema ${SUBSTRATE_CONTRACT.schema} to service_role;
`;
}

/**
 * @param {object} params
 * @param {string} [params.cwd] - Consumer checkout (default: process cwd).
 * @param {import('@forwardimpact/libutil/runtime').Runtime} params.runtime - Injected collaborators (fs, proc, clock).
 * @returns {Promise<number>}
 */
export async function runSubstrateInit({ cwd, runtime }) {
  const targetCwd = cwd ?? runtime.proc.cwd();
  // Supabase migration prefix: UTC YYYYMMDDHHMMSS.
  const ts = isoTimestamp(runtime.clock.now())
    .replace(/[-:TZ]/g, "")
    .slice(0, 14);
  const dir = path.join(targetCwd, "supabase", "migrations");
  const file = path.join(dir, `${ts}_substrate_contract.sql`);
  await runtime.fs.mkdir(dir, { recursive: true });
  await runtime.fs.writeFile(file, migrationSql());
  runtime.proc.stdout.write(
    formatSuccess(`Wrote starter migration ${file}`) + "\n",
  );
  return 0;
}
