/**
 * Generates field metadata for all service methods from proto files.
 * The output is a static ESM module that libmcp reads to generate schemas.
 */
export class CodegenMetadata {
  #base;

  /**
   * @param {object} base - CodegenBase instance that provides shared utilities
   */
  constructor(base) {
    if (!base) throw new Error("CodegenBase instance is required");
    this.#base = base;
  }

  /**
   * Generate metadata.js with the field descriptors for all service methods.
   * @param {string} generatedPath - Path to generated code directory
   * @returns {Promise<void>}
   */
  async run(generatedPath) {
    if (!generatedPath) throw new Error("generatedPath is required");

    const protoFiles = this.#base
      .collectProtoFiles({ includeTools: false })
      .filter((file) => !file.endsWith(this.#base.path.sep + "common.proto"));

    const metadata = {};

    for (const protoFile of protoFiles) {
      const parsed = this.#base.parseMetadata(protoFile);
      if (!parsed) continue;

      const serviceKey = `${parsed.packageName}.${parsed.serviceName}`;
      metadata[serviceKey] = parsed.methods;
    }

    const typesDir = this.#base.path.join(generatedPath, "types");
    this.#base.fs.mkdirSync(typesDir, { recursive: true });

    const content =
      `/** @generated by fit-codegen — do not edit */\n` +
      `export const metadata = ${JSON.stringify(metadata, null, 2)};\n`;

    this.#base.fs.writeFileSync(
      this.#base.path.join(typesDir, "metadata.js"),
      content,
    );
  }
}
