name: "Website: Monorepo Standard"

on:
  push:
    branches: [main]
    paths:
      - "websites/monorepo/**"
      - "libraries/libdoc/**"
      - ".github/workflows/website-monorepo.yaml"
      - ".github/workflows/website.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/website.yml
    with:
      site: monorepo
    secrets: inherit
