name: "Website: Co-Aligned"

on:
  push:
    branches: [main]
    paths:
      - "websites/coaligned/**"
      - "libraries/libdoc/**"
      - ".github/workflows/website-coaligned.yaml"
      - ".github/workflows/website.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/website.yml
    with:
      site: coaligned
    secrets: inherit
