name: "Website: Forward Impact"

on:
  push:
    branches: [main]
    paths:
      - "websites/fit/**"
      - "design/fit/**"
      - "libraries/libdoc/**"
      - ".github/workflows/website-fit.yaml"
      - ".github/workflows/website.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/website.yml
    with:
      site: fit
      copy-schema: true
    secrets: inherit
